//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinCalc.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            this.Items = new HashSet<ShoppingCartItem>();
        }
    
        public int Id { get; set; }
        public bool IsCurrent { get; set; }
        public float TotalPrice { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<ShoppingCartItem> Items { get; set; }
    }
}
